DROP TABLE IF EXISTS likes CASCADE;
CREATE TABLE likes
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  resource_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);