DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE comments 
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  resource_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);