DROP TABLE IF EXISTS ratings CASCADE;
CREATE TABLE ratings 
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  resource_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);